export const FIELD_ALIASES = {
  beds: [
    'beds',
    'bedrooms',
    'bedroom',
    'bed_count',
    'bedroom_count',
    'nbr_beds',
    'nbr_bedrooms',
    'no_of_bedrooms',
    'total_bedrooms',
    'bedrooms_total',
    'beds_total',
    'property_bedrooms',
    'building_bedrooms',
  ],
  baths: [
    'baths',
    'bathrooms',
    'bathroom',
    'bath_count',
    'bathroom_count',
    'nbr_baths',
    'nbr_bathrooms',
    'no_of_bathrooms',
    'total_bathrooms',
    'bathrooms_total',
    'baths_total',
    'property_bathrooms',
    'building_bathrooms',
  ],
  sqft: [
    'sqft',
    'square_feet',
    'squarefeet',
    'living_area',
    'livingarea',
    'building_sqft',
    'living_square_feet',
    'gross_living_area',
    'grosslivingarea',
  ],
  ownerName: [
    'owner_name',
    'owner',
    'full_name',
    'owner_full_name',
    'primary_owner_name',
  ],
  ownerOccupied: [
    'owner_occupied',
    'occupancy',
    'owneroccupancy',
    'owner_occupied_flag',
  ],
  lastSaleDate: [
    'last_sale_date',
    'sale_date',
    'lastsaledate',
    'last_transfer_date',
  ],
  estimatedValue: [
    'estimated_value',
    'value',
    'market_value',
    'house_value',
    'property_value',
    'estimated_market_value',
  ],
}